---
apiVersion: v1
kind: Service
metadata:
  name: recv
  namespace: default
spec:
  ports:
      - port: 80
        targetPort: 9080
        protocol: TCP
  selector:
        app: debug
---
apiVersion: v1
kind: Pod
metadata:
  name: receiver
  namespace: default
  labels:
    app: debug
spec:
  containers:
    - name: receiver
      image: localhost:15000/receiver
      imagePullPolicy: Always
      args:
        - "receiver.py"
        - "/app/config/debug-recv.json"
      volumeMounts:
        - mountPath: /app/config
          name: config
  volumes:
    - name: config
      hostPath:
        path: /app/config
