---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-dev
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.211-172.18.255.220
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: dev
  namespace: metallb-system
spec:
  ipAddressPools:
    - example-dev