---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-sta
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.200-172.18.255.210
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: sta
  namespace: metallb-system
spec:
  ipAddressPools:
    - example-sta