---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: example-sta
  namespace: metallb-system
spec:
  addresses:
    - 172.18.255.221-172.18.255.230
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: sta
  namespace: metallb-system
spec:
  ipAddressPools:
    - example-sta